#!/usr/bin/env python3
"""Generate or compare the tracked Ribos C parser snapshot."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
PROJECT = ROOT / "language" / "ribos"
GRAMMAR = PROJECT / "grammar" / "parser.gram"
TOKENS = PROJECT / "grammar" / "Tokens"
OUTPUT_C = PROJECT / "generated" / "parser.c"
OUTPUT_TOKENS = PROJECT / "generated" / "tokens.h"
OUTPUT_RECEIPT = (
    PROJECT / "generated" / "parser.receipt.json"
)
EXPECTED_PEGEN_REVISION = "9ccd5bb81edde823fb5fdbd51287f4a0ddfcd149"


def sha256(path: Path) -> str:
    """Return the lowercase SHA-256 digest for one file."""

    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def sha256_text(content: str) -> str:
    """Return the SHA-256 digest of one generated UTF-8 text artifact."""

    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def run_text(command: list[str], *, cwd: Path | None = None) -> str:
    """Run one bounded host command and return stripped stdout."""

    completed = subprocess.run(
        command,
        cwd=cwd,
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    return completed.stdout.strip()


def resolve_cpython_root(pegen_root: Path) -> Path:
    """Resolve and validate the CPython checkout that owns Tools/peg_generator."""

    resolved = pegen_root.resolve()
    if not (resolved / "pegen" / "__main__.py").is_file():
        raise ValueError(f"not a CPython Pegen root: {resolved}")
    cpython_root = resolved.parent.parent
    if not (cpython_root / "LICENSE").is_file():
        raise ValueError(f"missing CPython LICENSE: {cpython_root}")
    return cpython_root


def token_rows() -> list[tuple[str, int]]:
    """Parse the ordered named-token rows consumed by Pegen."""

    rows: list[tuple[str, int]] = []
    for raw_line in TOKENS.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        name = line.split()[0]
        rows.append((name, len(rows)))
    return rows


def render_token_header(grammar_digest: str, token_digest: str) -> str:
    """Render the tracked token-number snapshot shared with generated C."""

    enumerators = "\n".join(
        f"    {name} = {number}," for name, number in token_rows()
    )
    return f"""\
/* Generated from language/ribos/grammar/Tokens. Do not edit this file. */
/* RIBOS_GRAMMAR_SHA256: {grammar_digest} */
/* RIBOS_TOKENS_SHA256: {token_digest} */
#ifndef RIBOS_TOKENS_GENERATED_H
#define RIBOS_TOKENS_GENERATED_H

enum RibosTokenKind {{
{enumerators}
}};

#endif
"""


def render_parser_source(
    generated: Path,
    grammar_digest: str,
    token_digest: str,
    revision: str,
) -> str:
    """Add stable provenance to the Pegen-generated C translation unit."""

    body = generated.read_text(encoding="utf-8")
    prefix = f"""\
/* RIBOS-GENERATED-PARSER-SNAPSHOT */
/* RIBOS_GRAMMAR_SHA256: {grammar_digest} */
/* RIBOS_TOKENS_SHA256: {token_digest} */
/* RIBOS_PEGEN_REVISION: {revision} */
"""
    return prefix + body


def render_receipt(
    grammar_digest: str,
    token_digest: str,
    parser_source: str,
    token_header: str,
    revision: str,
) -> str:
    """Render deterministic generation provenance for the tracked snapshot."""

    receipt = {
        "generator": {
            "command": (
                "python -m pegen -q c language/ribos/grammar/parser.gram "
                "language/ribos/grammar/Tokens -o parser.c"
            ),
            "cpython_revision": revision,
            "exit_status": 0,
            "kind": "cpython-pegen-c",
        },
        "inputs": {
            "grammar": {
                "path": "language/ribos/grammar/parser.gram",
                "sha256": grammar_digest,
            },
            "tokens": {
                "path": "language/ribos/grammar/Tokens",
                "sha256": token_digest,
            },
        },
        "outputs": {
            "parser": {
                "path": "language/ribos/generated/parser.c",
                "sha256": sha256_text(parser_source),
            },
            "tokens": {
                "path": "language/ribos/generated/tokens.h",
                "sha256": sha256_text(token_header),
            },
        },
        "schema_version": 1,
    }
    return json.dumps(receipt, indent=2, sort_keys=True) + "\n"


def compare_or_write(path: Path, content: str, check: bool) -> bool:
    """Compare a snapshot in check mode or replace it in generation mode."""

    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == content:
        print(f"unchanged {path.relative_to(ROOT)}")
        return True
    if check:
        print(f"stale {path.relative_to(ROOT)}", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    print(f"generated {path.relative_to(ROOT)}")
    return True


def main(argv: list[str]) -> int:
    """Generate the parser only when explicitly invoked."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--pegen-root",
        type=Path,
        default=os.environ.get("RIBOS_PEGEN_ROOT"),
        required=os.environ.get("RIBOS_PEGEN_ROOT") is None,
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    try:
        pegen_root = args.pegen_root.resolve()
        cpython_root = resolve_cpython_root(pegen_root)
        revision = run_text(
            ["git", "rev-parse", "HEAD"],
            cwd=cpython_root,
        )
    except (OSError, ValueError, subprocess.CalledProcessError) as error:
        print(f"ribos parser generation setup failed: {error}", file=sys.stderr)
        return 2

    if revision != EXPECTED_PEGEN_REVISION:
        print(
            "ribos parser generation refused: "
            f"expected Pegen revision {EXPECTED_PEGEN_REVISION}, got {revision}",
            file=sys.stderr,
        )
        return 2

    grammar_digest = sha256(GRAMMAR)
    token_digest = sha256(TOKENS)

    with tempfile.TemporaryDirectory(prefix="ribos-pegen-") as temp_dir:
        raw_output = Path(temp_dir) / "parser.c"
        environment = os.environ.copy()
        environment["PYTHONPATH"] = str(pegen_root)
        command = [
            sys.executable,
            "-m",
            "pegen",
            "-q",
            "c",
            str(GRAMMAR),
            str(TOKENS),
            "-o",
            str(raw_output),
        ]
        try:
            subprocess.run(command, env=environment, check=True)
        except subprocess.CalledProcessError as error:
            print(f"Pegen generation failed: {error}", file=sys.stderr)
            return error.returncode or 1

        parser_source = render_parser_source(
            raw_output,
            grammar_digest,
            token_digest,
            revision,
        )
        token_header = render_token_header(grammar_digest, token_digest)
        receipt = render_receipt(
            grammar_digest,
            token_digest,
            parser_source,
            token_header,
            revision,
        )

    parser_ok = compare_or_write(OUTPUT_C, parser_source, args.check)
    tokens_ok = compare_or_write(OUTPUT_TOKENS, token_header, args.check)
    receipt_ok = compare_or_write(OUTPUT_RECEIPT, receipt, args.check)
    if not parser_ok or not tokens_ok or not receipt_ok:
        return 1

    print(
        "RIBOS-PEGEN-SNAPSHOT-OK "
        f"grammar={grammar_digest} tokens={token_digest} pegen={revision}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
