#!/usr/bin/env python3
"""Encode one binary as a deterministic freestanding C translation unit."""

from __future__ import annotations

import argparse
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--symbol", default="ribon_embedded_payload")
    args = parser.parse_args()
    data = args.input.read_bytes()
    rows = [
        "    " + ", ".join(f"0x{byte:02x}" for byte in data[offset : offset + 12]) + ","
        for offset in range(0, len(data), 12)
    ]
    source = (
        "/* Generated by tools/embed_binary.py; do not edit. */\n"
        "#include <stdint.h>\n\n"
        f"const unsigned char {args.symbol}[] = {{\n"
        + "\n".join(rows)
        + "\n};\n"
        f"const uint64_t {args.symbol}_size = sizeof({args.symbol});\n"
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(source, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
