#!/usr/bin/env python3
"""Generate a deterministic immutable Ribon plugin registry and product tuple."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ARCHITECTURE_MASKS = {
    "x86_64": "RIBON_ARCH_MASK_X86_64",
    "aarch64": "RIBON_ARCH_MASK_AARCH64",
    "riscv64": "RIBON_ARCH_MASK_RISCV64",
}


def load_manifest(path: Path) -> dict[str, object]:
    """Load and validate the source-owned registry manifest."""

    manifest = json.loads(path.read_text(encoding="utf-8"))
    plugins = manifest.get("plugins")
    if (
        manifest.get("product_id") != "host-reference"
        or manifest.get("environment") != "host"
        or manifest.get("mode") != "normal"
        or not isinstance(plugins, list)
        or not plugins
    ):
        raise ValueError("invalid host-reference manifest")
    ids: list[str] = []
    symbols: set[str] = set()
    for item in plugins:
        if not isinstance(item, dict):
            raise ValueError("plugin entry must be an object")
        plugin_id = item.get("id")
        symbol = item.get("symbol")
        if (
            not isinstance(plugin_id, str)
            or not plugin_id
            or not isinstance(symbol, str)
            or not symbol.startswith("ribon_")
        ):
            raise ValueError("plugin id and symbol must be stable strings")
        ids.append(plugin_id)
        if symbol in symbols:
            raise ValueError(f"duplicate plugin symbol: {symbol}")
        symbols.add(symbol)
    if ids != sorted(ids) or len(ids) != len(set(ids)):
        raise ValueError("plugin IDs must be unique and sorted")
    return manifest


def render(manifest: dict[str, object], architecture: str) -> str:
    """Render a C registry without constructors or weak discovery."""

    plugins = manifest["plugins"]
    assert isinstance(plugins, list)
    externs = "\n".join(
        f"extern const struct RibonPluginDescriptor {item['symbol']};"
        for item in plugins
    )
    pointers = "\n".join(
        f"    &{item['symbol']}," for item in plugins
    )
    return f"""/* Generated by tools/generate_plugin_registry.py; do not edit. */
#include <Ribon/plugin/registry.h>

{externs}

static const struct RibonPluginDescriptor *const generated_plugins[] = {{
{pointers}
}};

static const struct RibonPluginRegistry generated_registry = {{
    .size = sizeof(generated_registry),
    .abi_version = RIBON_CORE_ABI_VERSION,
    .plugins = generated_plugins,
    .plugin_count = (uint32_t)(sizeof(generated_plugins) / sizeof(generated_plugins[0])),
}};

static const struct RibonProductDescriptor generated_product = {{
    .magic = RIBON_PRODUCT_DESCRIPTOR_MAGIC,
    .size = sizeof(generated_product),
    .abi_version = RIBON_CORE_ABI_VERSION,
    .id = "host-reference",
    .architecture_mask = {ARCHITECTURE_MASKS[architecture]},
    .environment_mask = RIBON_ENV_MASK_HOST,
    .mode_mask = RIBON_MODE_MASK(RIBON_MODE_NORMAL),
    .max_plugins = 16u,
    .required_capabilities =
        RIBON_CAP_BOOT_SOURCE_READ |
        RIBON_CAP_MONOTONIC_TIMER |
        RIBON_CAP_ARCHITECTURE |
        RIBON_CAP_IMAGE_ELF64 |
        RIBON_CAP_BOOT_PROTOCOL |
        RIBON_CAP_HANDOFF |
        RIBON_CAP_ENTRY_CONTRACT |
        RIBON_CAP_BOOT_CONFIRMATION,
    .allowed_capabilities =
        RIBON_CAP_BOOT_SOURCE_READ |
        RIBON_CAP_MONOTONIC_TIMER |
        RIBON_CAP_ARCHITECTURE |
        RIBON_CAP_IMAGE_ELF64 |
        RIBON_CAP_BOOT_PROTOCOL |
        RIBON_CAP_HANDOFF |
        RIBON_CAP_ENTRY_CONTRACT |
        RIBON_CAP_BOOT_CONFIRMATION,
    .limits = {{
        .max_memory_regions = 256u,
        .max_load_segments = 32u,
        .max_components = 32u,
        .max_retries = 2u,
        .max_input_bytes = 64ull * 1024ull * 1024ull,
        .max_handoff_bytes = 64ull * 1024ull,
        .arena_bytes = 256ull * 1024ull,
        .operation_deadline_ms = 30000u,
    }},
}};

const struct RibonPluginRegistry *ribon_generated_plugin_registry(void) {{
    return &generated_registry;
}}

const struct RibonProductDescriptor *ribon_generated_product_descriptor(void) {{
    return &generated_product;
}}
"""


def main() -> int:
    """Generate the requested architecture-specific product source."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--architecture", choices=sorted(ARCHITECTURE_MASKS), required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    manifest = load_manifest(args.manifest)
    output = render(manifest, args.architecture)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
