#ifndef RIBON_CORE_STATUS_H
#define RIBON_CORE_STATUS_H

/** @brief Ribon Core와 registry 검증의 공통 결과다. */
enum RibonCoreStatus {
    RIBON_CORE_STATUS_OK = 0,
    RIBON_CORE_STATUS_BAD_ARGUMENT = -1,
    RIBON_CORE_STATUS_BAD_ABI = -2,
    RIBON_CORE_STATUS_BAD_MODE = -3,
    RIBON_CORE_STATUS_BAD_LIMIT = -4,
    RIBON_CORE_STATUS_OUT_OF_CAPACITY = -5,
    RIBON_CORE_STATUS_BAD_ALIGNMENT = -6,
    RIBON_CORE_STATUS_MISSING_CAPABILITY = -7,
    RIBON_CORE_STATUS_FORBIDDEN_CAPABILITY = -8,
    RIBON_CORE_STATUS_INVALID_DESCRIPTOR = -9,
    RIBON_CORE_STATUS_DUPLICATE_PROVIDER = -10,
    RIBON_CORE_STATUS_DEPENDENCY_CYCLE = -11,
    RIBON_CORE_STATUS_BAD_STATE = -12,
    RIBON_CORE_STATUS_PHASE_INVERSION = -13,
    RIBON_CORE_STATUS_AMBIGUOUS_SELECTION = -14,
};

#endif
